name: AWS Setup
description: Configure AWS credentials and retrieve secrets from AWS Secrets Manager with optional environment variable prefix

inputs:
  aws-role:
    description: 'The AWS IAM role ARN to assume'
    required: false
    default: 'arn:aws:iam::856284715153:role/GithubActionsOidcCdkDeployRole'
  secret-id:
    description: 'AWS Secrets Manager secret ID for environment-specific secrets'
    required: false
  env-prefix:
    description: 'Prefix to add to environment variables (e.g., "VITE_" for frontend)'
    required: false
    default: ''

runs:
  using: 'composite'
  steps:
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: ${{ inputs.aws-role }}
        aws-region: us-east-1

    - name: Retrieve secrets from AWS Secrets Manager
      if: inputs.secret-id != ''
      shell: bash
      run: |
        SECRET_JSON=$(aws secretsmanager get-secret-value --secret-id ${{ inputs.secret-id }} --query 'SecretString' --output text)
        echo "$SECRET_JSON" | jq -r 'to_entries | .[] | select(.value | type == "string") | .value' | while read -r value; do
          echo "::add-mask::$value"
        done

        if [ -n "${{ inputs.env-prefix }}" ]; then
          echo "$SECRET_JSON" | jq -r 'to_entries | .[] | select(.value | type == "string") | "${{ inputs.env-prefix }}\(.key)=\(.value)"' >> $GITHUB_ENV
        else
          echo "$SECRET_JSON" | jq -r 'to_entries | .[] | select(.value | type == "string") | "\(.key)=\(.value)"' >> $GITHUB_ENV
        fi
