export enum ErrorTypeEnum {
  REST = 'REST',
  REST_NETWORK = 'REST_NETWORK',
  CLIENT_NOT_INITIALIZED = 'CLIENT_NOT_INITIALIZED',

  MAPPER = 'MAPPER',
  SCHEMA_VALIDATION = 'SCHEMA_VALIDATION',

  AUTH_ERROR = 'AUTH_ERROR',
  THUNK = 'THUNK',
  APP_ERROR_BOUNDARY = 'APP_ERROR_BOUNDARY',
}
